### PR TITLE
Add language configuration

### PR DESCRIPTION
**Pull request by angelkurten**
Add configuration for the AI Tutor speaks other languages

### CODE REVIEW

**Comment by Anakin008** [comment]
At a native level. There are a lot of problems when it comes to slang and professional/specific topics in a foreign language.

**Review by LifeBringer — APPROVED** [review]
LGTM

**Comment by LifeBringer** [comment]
> At a native level. There are a lot of problems when it comes to slang and professional/specific topics in a foreign language.

That's true, but that's an upstream issue that will be resolved with the LLM itself.

**Review by alexthehurst — COMMENTED** [review]
@angelkurten did you consider adding this as a configuration which is defined and managed along with the other configurations? It seems similar.

Have you been able to verify that the output is still high quality and the non-English modes use the target language even where the prompt has scripted responses in English?

**Comment by JushBJJ** [comment]
> At a native level. There are a lot of problems when it comes to slang and professional/specific topics in a foreign language.

Which language is this?

**Comment by angelkurten** [comment]
@alexthehurst I tried, but to add "language" to the config command we need a language options list, and is very complicated to add all the countries to the JSON

@LifeBringer can you approve the merge again pls

**Comment by angelkurten** [comment]
@alexthehurst I speak Spanish and I verify the output is still high quality

**Review by ggermade — APPROVED** [review]
Looks quite straightforward. I would suggest providing language options, but this flexible style should work too

**Comment by JushBJJ** [comment]
Finally got the time to test it out. Here are some screenshots that we could add to the README.md. There should also be a disclaimer that GPT-4 isn't perfect and sentence structure may not be correct. I spoke to my Russian friend and said the Russian screenshot sentences don't build correctly unless each word is translated separately.

# Chinese
image
image

# Russian
image

# Spanish
image

# Tagalog
image

# Arabic
image

**Comment by angelkurten** [comment]
@JushBJJ i update the de readme.md and docs.md

**Comment by JushBJJ** [comment]
> @JushBJJ i update the de readme.md and docs.md

Thanks. I just hit my GPT-4 limit so I cant test again till its 12am for me, but I think Mr. Ranedeer should specifically say to the student, after outputting the configurations (_only in its introduction_), to type `/language <any language>` to whatever they like. Emphasizing that it can respond with **any** language that it can do.

**Review by BKR-dev — APPROVED** [review]

**Comment by BKR-dev** [comment]
it also works well in german, even after setting it up in english and switching to german mid plan

**Review by JushBJJ — APPROVED** [review]

**Pull request merged**
