### PR TITLE
Mr. Ranedeer with code interpreter - v2.7

### PR DESCRIPTION
**Pull request by JushBJJ**
# Mr. Ranedeer with code interpreter - v2.7

## Description

This PR is for the next version of Mr. Ranedeer. Now that code interpreter is released, new enhancements can be made.

## Changes

1. Re-arranged prompt to improve effectiveness
2. Added "Overall Rules to follow" header
3. Added a little personality to Mr. Ranedeer
4. Gave Mr. Ranedeer more freedom on what to say
5. Added `Prerequisite` and `Main Curriculum` examples as a strong guide
6. Removed `teach` function
7. Moved Mr. Ranedeer's thoughts onto the code environment
8. Removed token check & magic number as it is now no longer needed
9. Mr. Ranedeer will now wait for you response after it asks you a question
10. Reworked algorithm for `Curriculum` and `Lesson`
11. Added a standard for `Config Example`
12. Moved function rules to the bottom of the prompt
13. Recall personality and rules
14. Recall curriculum
15. Write instructions, emojis, and observations of the student
16. Ability to change the configuration automatically if needed
17. Ability to solve mathematical problems in python first in the /test command before showing them to the student.
18. Improve question accuracy by only giving one question at a time #40 
19. Create curriculum by uploading `.txt` files
20. Added configuration wizard #33

### Tests

* [x] The new feature/fix has been tested to an extent that it is working as expected.

### Additional Checklists

* [x] https://github.com/JushBJJ/Mr.-Ranedeer-AI-Tutor/issues/26
* [x] https://github.com/JushBJJ/Mr.-Ranedeer-AI-Tutor/issues/40
* [x] https://github.com/JushBJJ/Mr.-Ranedeer-AI-Tutor/issues/33
* [x] https://github.com/JushBJJ/Mr.-Ranedeer-AI-Tutor/issues/48
* [x] ~~A `Worksheet` command where Mr. Ranedeer will generate you one week's worth of questions for you to finish.~~
* [x] https://github.com/JushBJJ/Mr.-Ranedeer-AI-Tutor/issues/73

### CODE REVIEW

**Comment by sawyerbutton** [comment]
> # Mr. Ranedeer with code interpreter - v2.7
> ## Description
> This PR is for the next version of Mr. Ranedeer. Now that code interpreter is released, new enhancements can be made.
> 
> ## Changes
> 1. Re-arranged prompt to improve effectiveness
> 2. Added "Overall Rules to follow" header
> 3. Added a little personality to Mr. Ranedeer
> 4. Gave Mr. Ranedeer more freedom on what to say
> 5. Added `Prerequisite` and `Main Curriculum` examples as a strong guide
> 6. Removed `teach` function
> 7. Moved Mr. Ranedeer's thoughts onto the code environment
> 8. Removed token check & magic number as it is now no longer needed
> 9. Mr. Ranedeer will now wait for you response after it asks you a question
> 10. Reworked algorithm for `Curriculum` and `Lesson`
> 11. Added a standard for `Config Example`
>     12 Moved function rules to the bottom of the prompt
> 
> ### Tests
> * [ ]  The new feature/fix has been tested to an extent that it is working as expected.
> 
> ### Additional Checklists
> * [ ]  [AI Tutor will forget it's prompt after 8k tokens #26](https://github.com/JushBJJ/Mr.-Ranedeer-AI-Tutor/issues/26)
> * [ ]  [Improve question accuracy by only giving one question at a time #40](https://github.com/JushBJJ/Mr.-Ranedeer-AI-Tutor/issues/40)
> * [ ]  [Add an interactive mode to choose preferences #33](https://github.com/JushBJJ/Mr.-Ranedeer-AI-Tutor/issues/33)
> * [ ]  [AI will forget the plan If I ask some detail info of some step and then return #48](https://github.com/JushBJJ/Mr.-Ranedeer-AI-Tutor/issues/48)
> * [ ]  A `Worksheet` command where Mr. Ranedeer will generate you one week's worth of questions for you to finish.

Looking forward to this PR.

**Comment by JushBJJ** [comment]
New features added:
- Recall personality and rules
- Recall curriculum
- Write instructions, emojis, and observations of the student
- Ability to change the configuration if needed
- Ability to solve mathematical problems in python first in the `/test` command before showing them to the student.

**Comment by JushBJJ** [comment]
More checklists before release:
* [ ] Add config wizard reference to `Guides/Config Guide.md`
* [ ] Redirect user to the wizard when they do `/config` command
* [ ] Create new set of screenshots for README.md
* [ ] Test all Ranedeer Tools
* [ ] Last minute bug fixes

**Comment by JushBJJ** [comment]
Very close to releasing now

**Pull request merged**
